# Generated by Django 3.0.4 on 2020-05-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200507_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_meta',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок'),
        ),
    ]
