# Generated by Django 3.0.4 on 2020-05-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_article_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_meta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок'),
        ),
    ]
