# Generated by Django 3.0.6 on 2020-05-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200507_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.TextField(verbose_name='Дата публикации'),
        ),
    ]
